### ISSUE TITLE
Make participant list more readable

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-customization-files#26]
The EA team has requested a more readable view for the participant list. Currently it gets cut off pretty quickly.

Example: https://events.canonical.com/event/28/registrations/participants

A partial solution would be to change `--full-width` to 100% on these pages only. Another option might be to introduce horizontal scrolling for that table. This would be especially prudent for small screen sizes, as even with a 100% view, the participant list is unreadable on mobile.

@petesfrench @akbarkz can you add this to your planning? If this can be done before the Madrid sprints it would be very helpful.

**Comment by petesfrench** [comment]
I have added this and the other issue to our backlog, we will try to fit them in before the sprint.
