### ISSUE TITLE
Email notification is generated but no email sent

### ISSUE THREAD

**Issue by sukso96100** [canonical/canonical-indico-customization-files#30]
Hello, It seems like if I try to send an email through Management - Participant Roles - Send emails buttons, It does generates some actions and logs, But seems like email isn't really being sent from noreply+events@canonical.com

This is also seem to be same for abstract notification. I tried to click Judge button to generate email notification after configuring Email notification on Call for Abstracts menu. It does generates some email action and logs, but no email actually sent. Email isn't really delivered to my inbox not even spam.

So https://events.canonical.com/event/47 is our event entry on Indico. Could someone can check if it's misconfiguration issue on our side or issue with indico instance? - Feel free to let me know if more information required.

**Comment by aaronprisk** [comment]
Hello youngbin,
Thank you for letting us know. There was a backend mail delivery issue that should be resolved now. Can you please try to initiate an email notification and let me know if it's successful?

**Comment by sukso96100** [comment]
Hello @aaronprisk :) Surely, will try and close this issue if problem seem to be resolved. Thanks :)

**Comment by sukso96100** [comment]
Seem like email is now working well. Thanks :)
![image](https://github.com/canonical/canonical-indico-customization-files/assets/1916739/f1fe291a-f490-4421-ace5-f0be7d21a323)
